// <auto-generated />
using System;
using BloodDonation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodDonation.Migrations
{
    [DbContext(typeof(BloodDonationContext))]
    [Migration("20251130184927_InitialTables")]
    partial class InitialTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodDonation.Models.BloodTypes", b =>
                {
                    b.Property<int>("BloodTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BloodTypeId"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("BloodTypeId");

                    b.ToTable("BloodTypes");

                    b.HasData(
                        new
                        {
                            BloodTypeId = 1,
                            Type = "A+"
                        },
                        new
                        {
                            BloodTypeId = 2,
                            Type = "A-"
                        },
                        new
                        {
                            BloodTypeId = 3,
                            Type = "B+"
                        },
                        new
                        {
                            BloodTypeId = 4,
                            Type = "B-"
                        },
                        new
                        {
                            BloodTypeId = 5,
                            Type = "AB+"
                        },
                        new
                        {
                            BloodTypeId = 6,
                            Type = "AB-"
                        },
                        new
                        {
                            BloodTypeId = 7,
                            Type = "O+"
                        },
                        new
                        {
                            BloodTypeId = 8,
                            Type = "O-"
                        });
                });

            modelBuilder.Entity("BloodDonation.Models.DonorProfile", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonorId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHealthyForDonation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIdentityHidden")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DonorId");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("DonorProfile");
                });

            modelBuilder.Entity("BloodDonation.Models.Locations", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Districts")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Districts = "Beirut"
                        },
                        new
                        {
                            LocationId = 2,
                            Districts = "Baabda"
                        },
                        new
                        {
                            LocationId = 3,
                            Districts = "Aley"
                        },
                        new
                        {
                            LocationId = 4,
                            Districts = "Chouf"
                        },
                        new
                        {
                            LocationId = 5,
                            Districts = "Keserwan"
                        },
                        new
                        {
                            LocationId = 6,
                            Districts = "Matn"
                        },
                        new
                        {
                            LocationId = 7,
                            Districts = "Jbeil"
                        },
                        new
                        {
                            LocationId = 8,
                            Districts = "Zahle"
                        },
                        new
                        {
                            LocationId = 9,
                            Districts = "Baalbek"
                        },
                        new
                        {
                            LocationId = 10,
                            Districts = "Hermel"
                        },
                        new
                        {
                            LocationId = 11,
                            Districts = "Tripoli"
                        },
                        new
                        {
                            LocationId = 12,
                            Districts = "Miniyeh-Danniyeh"
                        },
                        new
                        {
                            LocationId = 13,
                            Districts = "Zgharta"
                        },
                        new
                        {
                            LocationId = 14,
                            Districts = "Koura"
                        },
                        new
                        {
                            LocationId = 15,
                            Districts = "Batroun"
                        },
                        new
                        {
                            LocationId = 16,
                            Districts = "Bcharre"
                        },
                        new
                        {
                            LocationId = 17,
                            Districts = "Akkar"
                        },
                        new
                        {
                            LocationId = 18,
                            Districts = "Saida"
                        },
                        new
                        {
                            LocationId = 19,
                            Districts = "Tyre"
                        },
                        new
                        {
                            LocationId = 20,
                            Districts = "Jezzine"
                        },
                        new
                        {
                            LocationId = 21,
                            Districts = "Nabatieh"
                        },
                        new
                        {
                            LocationId = 22,
                            Districts = "Bint Jbeil"
                        },
                        new
                        {
                            LocationId = 23,
                            Districts = "Marjeyoun"
                        },
                        new
                        {
                            LocationId = 24,
                            Districts = "Hasbaya"
                        });
                });

            modelBuilder.Entity("BloodDonation.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("BloodDonation.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BloodDonation.Models.DonorProfile", b =>
                {
                    b.HasOne("BloodDonation.Models.BloodTypes", "BloodType")
                        .WithMany()
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonation.Models.Locations", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonation.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonation.Models.PasswordReset", b =>
                {
                    b.HasOne("BloodDonation.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
